version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "gradle"
    groups:
      gradle-security:
        patterns: ["*"]
        update-types: ["security"]
      gradle-major:
        patterns: ["*"]
        update-types: ["major"]
      gradle-minor:
        patterns: ["*"]
        update-types: ["minor"]
      gradle-patch:
        patterns: ["*"]
        update-types: ["patch"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "npm"
    groups:
      npm-security:
        patterns: ["*"]
        update-types: ["security"]
      npm-major:
        patterns: ["*"]
        update-types: ["major"]
      npm-minor:
        patterns: ["*"]
        update-types: ["minor"]
      npm-patch:
        patterns: ["*"]
        update-types: ["patch"]
