name: Run game tests

on:
  workflow_call:

jobs:
  game-tests:
    runs-on: ubuntu-latest
    name: Run game tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Read properties file and set as env
        run: |
          while IFS= read -r line || [[ -n "$line" ]]; do
            if [[ $line == \#* ]] || [[ -z $line ]]; then
              continue # Skip comments and empty lines
            fi
            IFS='=' read -r key value <<< "$line"
            key=$(echo $key | xargs) # Trim key
            value=$(echo $value | xargs) # Trim value
            if [ ! -z "$key" ]; then
              echo "Setting $key=$value"
              echo "$key=$value" >> $GITHUB_ENV
            fi
          done < ./gradle.properties
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.java_version }}
          distribution: 'temurin'
          cache: 'gradle'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./build/fg_cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Run game test server
        run: ./gradlew test
        